Feat/linux support
miru-project/miru-app pull request #251
Opened 2024-04-11 03:06 UTC by appdevelpo

- Use  `jsocre` rather than `qjs`.
- some extensions are not working
- Webview haven't implemented yet, so anilist and webview in `detail` won't working too 

## Screenshot
### latest
![image](https://github.com/miru-project/miru-app/assets/56633229/02ebb4b7-0cb0-44f4-b0b0-6968fd461244)
### detail
![image](https://github.com/miru-project/miru-app/assets/56633229/b596dbac-4ccd-41a5-9fcc-651625b5c535)
### watch
![image](https://github.com/miru-project/miru-app/assets/56633229/c4e69227-d15a-4b0d-9380-8db1b04aebba)

2024-04-11 04:07 UTC, appdevelpo commented
### fix  `libmpv.so.1: cannot open shared object file: No such file or directory `
```
sudo ln -s /usr/lib/libmpv.so /usr/lib/libmpv.so.1
```

2024-04-14 13:55 UTC, MiaoMint requested changes

2024-04-14 13:55 UTC, MiaoMint commented on lib/utils/bt_server.dart
> +        "https://api.github.com/repos/appdevelpo/bt-server/releases/latest"; //  temporary url
改回组织的地址

2024-04-16 03:46 UTC, MiaoMint approved these changes

2024-04-16 03:49 UTC, merged